repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.7
    hooks:
      - id: ruff-check
        types_or: [ python, pyi, pyproject ]
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        name: mypy (categories_service)
        files: ^categories_service/
        additional_dependencies:
          - pydantic>=2.12.5
          - sqlalchemy>=2.0.48
          - fastapi>=0.135.1
      - id: mypy
        name: mypy (posts_service)
        files: ^posts_service/
        additional_dependencies:
          - pydantic>=2.12.5
          - sqlalchemy>=2.0.48
          - fastapi>=0.135.1

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
